global:
  scrape_interval: 15s # Intervalo de recolección de datos

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_app'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Cambia a tu configuración de aplicación Node.js
